# Generated by Django 2.2.24 on 2021-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
